apiVersion: apps/v1
kind: ContainerApp
metadata:
  name: update-gpt-instructions
  namespace: augmented-teams
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: update-gpt-instructions
        feature: update-gpt-instructions
    spec:
      containers:
      - name: update-gpt-instructions
        image: augmentedteamacr.azurecr.io/update-gpt-instructions:latest
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: github-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - python
            - startup.py
            - --health-check
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - startup.py
            - --health-check
          initialDelaySeconds: 10
          periodSeconds: 10

