openapi: 3.1.0
info:
  title: Git Integration Service
  version: 1.0.0
  description: REST API for Git operations including committing text, documents, and managing repository changes
servers:
  - url: http://localhost:8001
    description: Local Git Integration Service
  - url: https://ubiquitous-fiesta-4xrwxq44wh57q6-8001.app.github.dev
    description: GitHub Codespace Git Integration Service

paths:
  /:
    get:
      operationId: healthCheck
      summary: Health check
      description: Check if the Git Integration Service is running
      responses:
        "200":
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  repo:
                    type: string

  /status:
    get:
      operationId: getRepositoryStatus
      summary: Get repository status
      description: Get current repository status including pending changes
      responses:
        "200":
          description: Repository status
          content:
            application/json:
              schema:
                type: object
                properties:
                  repo_path:
                    type: string
                  branch:
                    type: string
                  has_changes:
                    type: boolean
                  changes:
                    type: array
                    items:
                      type: string
                  error:
                    type: string

  /commit/text:
    post:
      operationId: commitTextContent
      summary: Commit text content to a file
      description: Write text content to a file and commit it to the repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - file_path
              properties:
                content:
                  type: string
                  description: The text content to write
                file_path:
                  type: string
                  description: Where to write the file (relative to repo root)
                commit_message:
                  type: string
                  description: Optional commit message
      responses:
        "200":
          description: Text content committed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string
        "500":
          description: Error committing content

  /commit/document:
    post:
      operationId: commitDocument
      summary: Commit uploaded document
      description: Upload and commit a document file to the repository
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - file_path
              properties:
                file:
                  type: string
                  format: binary
                  description: The uploaded file
                file_path:
                  type: string
                  description: Where to save the file (relative to repo root)
                commit_message:
                  type: string
                  description: Optional commit message
      responses:
        "200":
          description: Document committed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string
        "500":
          description: Error committing document

  /push:
    post:
      operationId: pushChanges
      summary: Push changes to remote
      description: Push committed changes to the remote repository
      responses:
        "200":
          description: Changes pushed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  output:
                    type: string
        "500":
          description: Error pushing changes

  /commit-and-push:
    post:
      operationId: commitAndPush
      summary: Commit text content and push
      description: Commit text content to a file and push to remote in one operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - file_path
              properties:
                content:
                  type: string
                  description: The text content to write
                file_path:
                  type: string
                  description: Where to write the file (relative to repo root)
                commit_message:
                  type: string
                  description: Optional commit message
      responses:
        "200":
          description: Content committed and pushed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string
        "500":
          description: Error committing or pushing

components:
  schemas:
    CommitRequest:
      type: object
      required:
        - content
        - file_path
      properties:
        content:
          type: string
          description: The text content to write
        file_path:
          type: string
          description: Where to write the file (relative to repo root)
        commit_message:
          type: string
          description: Optional commit message
    CommitResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        commit_hash:
          type: string
        file_path:
          type: string
