classDiagram
    namespace actions {
        class Base Action {
            +inject_instructions()
            +load_relevant_content_+_inject_into_instructions()
            +save_content_changes()
        }
        class Behavior Action State {
            +track_current_action()
            +track_completed_actions()
            +determine_next_action()
            +pause_workflow()
            +resume_workflow()
        }
        class Content {
            +render_outputs()
            +synchronize_formats()
            +save_knowledge_graph()
            +load_rendered_content()
            +present_rendered_content()
        }
        class Guardrails {
            +provide_required_context()
            +guide_planning_decisions()
            +define_recommended_human_activity()
        }
        class Workflow State {
            +track_current_action()
            +track_completed_actions()
            +determine_next_action()
            +pause_workflow()
            +resume_workflow()
        }
    }

    namespace actions.build {
        class BuildKnowledgeAction {
            +inject_knowledge_graph_template()
            +inject_builder_instructions()
            +save_knowledge_graph()
        }
    }

    namespace actions.clarify {
        class GatherContextAction {
            +inject_gather_context_instructions()
            +inject_questions_and_evidence()
        }
    }

    namespace actions.render {
        class RenderOutputAction {
            +inject_render_output_instructions()
            +inject_templates()
            +inject_transformers()
            +load_+_inject_structured_content()
        }
        class Renderer {
            +render_complex_output()
            +render_outputs_using_components_in_context()
        }
        class Template {
            +define_output_structure()
            +transform_content()
            +load_template()
        }
    }

    namespace actions.rules {
        class Rule {
            +validate_content()
            +find_behavior_specific_rules_from_context()
            +find_common_bot_rules_from_context()
            +load_+_inject_diagnostics_results()
            +suggest_corrections()
            +provide_examples_-_do()
            +provide_examples_-_dont()
            +specialized_examples()
        }
        class ValidateRulesAction {
            +inject_common_bot_rules()
            +inject_behavior_specific_rules()
            +load_+_inject_content_for_validation()
        }
    }

    namespace actions.strategy {
        class PlanningAction {
            +inject_planning_instructions()
            +inject_decision_criteria_and_assumptions()
        }
    }

    namespace actions.validate {
        class CorrectBotAction {
            +inject_correct_bot_instructions()
            +load_+_inject_diagnostics_results()
        }
    }

    namespace agile_bot.bots.base_bot.src.synchronizers {
        class Synchronizer {
            +synchronizes_formats()
            +extracts_from_source()
            +renders_to_target()
            +validates_sync()
            +get_source_format()
            +get_target_format()
            +get_extractor()
            +get_renderer()
        }
    }

    namespace agile_bot.bots.story_bot.src.story_bot_cli {
        class StoryBotCLI {
            +bootstraps_environment()
            +delegates_to_basebotcli()
            +executes_cli()
            +get_bot_directory()
            +get_workspace_directory()
            +get_bot_name()
            +get_bot_config_path()
        }
    }

    namespace agile_bot.bots.story_bot.src.story_bot_mcp_server {
        class ActionStateManager {
            +closes_current_action()
            +loads_action_state()
            +determines_next_action()
            +transitions_to_next_action()
            +detects_behavior_completion()
            +transitions_to_next_behavior()
            +returns_transition_result()
            +handles_out-of-order_confirmation()
            +validates_human_confirmation()
            +persists_confirmation()
            +get_state_file()
            +get_current_action()
            +get_next_action()
            +get_behavior_complete()
            +get_out_of_order_confirmations()
        }
        class BehaviorToolGenerator {
            +generates_behavior_tool_function()
            +routes_to_behavior()
            +routes_to_action()
            +executes_action()
            +returns_result()
            +handles_missing_action()
            +loads_action_state()
            +get_tool_name()
            +get_tool_description()
            +get_trigger_patterns()
        }
        class StoryBotMCPServer {
            +bootstraps_environment()
            +creates_bot_instance()
            +creates_fastmcp_server()
            +registers_bot_tool()
            +registers_behavior_tools()
            +registers_utility_tools()
            +delegates_to_bot()
            +runs_mcp_server()
            +get_bot_directory()
            +get_workspace_directory()
            +get_bot()
            +get_server()
        }
        class WorkingDirectoryManager {
            +gets_working_directory()
            +sets_working_directory()
            +validates_path()
            +updates_environment()
            +updates_bot_config()
            +persists_to_config()
            +returns_previous_directory()
            +get_working_directory()
            +get_previous_directory()
            +get_persisted()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.domain_model.domain_model_synchronizer {
        class DomainModelSynchronizer : Synchronizer {
            +syncs_crc_text_with_story_graph()
            +extracts_domain_concepts()
            +renders_domain_concepts()
            +validates_crc_format()
            +preserves_module_paths()
            +get_crc_path()
            +get_story_graph_path()
            +get_domain_concepts()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_epic {
        class StoryIOEpic {
            +owns_features()
            +calculates_total_stories()
            +renders_epic_section()
            +validates_epic_structure()
            +get_name()
            +get_description()
            +get_features()
            +get_total_stories()
            +get_sequential_order()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_feature {
        class StoryIOFeature {
            +owns_stories()
            +calculates_story_count()
            +renders_feature_section()
            +validates_feature_structure()
            +get_name()
            +get_description()
            +get_stories()
            +get_story_count()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_increment {
        class StoryIOIncrement {
            +owns_story_assignments()
            +manages_priorities()
            +calculates_capacity()
            +renders_increment_view()
            +validates_increment_structure()
            +get_number()
            +get_name()
            +get_stories()
            +get_capacity()
            +get_priority_order()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_renderer {
        class StoryIORenderer {
            +renders_epic_cells()
            +renders_feature_cells()
            +renders_story_cells()
            +renders_increment_lanes()
            +calculates_layout()
            +formats_xml()
            +get_cell_style()
            +get_layout_config()
            +get_xml_formatter()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_story {
        class StoryIOStory {
            +owns_acceptance_criteria()
            +owns_increment_assignment()
            +renders_story_card()
            +validates_story_format()
            +calculates_position()
            +get_name()
            +get_description()
            +get_acceptance_criteria()
            +get_increment()
            +get_priority()
            +get_position()
        }
    }

    namespace agile_bot.bots.story_bot.src.synchronizers.story_io.story_io_synchronizer {
        class StoryIOSynchronizer : Synchronizer {
            +syncs_story_graph_with_drawio()
            +extracts_stories_from_drawio()
            +renders_stories_to_drawio()
            +manages_story_positions()
            +updates_increments()
            +validates_story_structure()
            +get_story_graph_path()
            +get_drawio_path()
            +get_increments()
            +get_epics()
            +get_stories()
        }
    }

    namespace bot {
        class Base Bot {
            +executes_actions()
            +track_activity()
            +route_to_behaviors_and_actions()
            +persist_content()
            +manage_project_state()
            +render()
        }
        class Behavior {
            +perform_configured_actions()
            +invoke_on_trigger_words()
            +inject_instructions()
            +provide_guardrails()
            +provide_rules()
            +provide_content_specs()
            +gets_action_by_name()
            +gets_actions_in_sequence()
        }
        class Behavior Workflow {
            +determine_next_action()
            +track_state()
        }
        class Specific Bot {
            +provide_behavior_config()
            +provide_mcp_config()
            +provide_renderers()
            +provide_extractors()
            +provide_synchronizer()
            +provide_trigger_words()
        }
    }

    namespace display_panel.extension {
        class BehaviorActionSection {
            +wraps_behaviors()
            +renders_behavior_action_tree()
            +shows_current_action_indicator()
            +shows_completed_status_indicator()
            +shows_pending_indicator()
            +handles_navigation_to_previous_action()
            +handles_navigation_to_next_action()
            +handles_rerun_current_action()
            +handles_behavior_click_to_execute()
            +handles_action_click_to_execute()
            +expands_and_collapses_behaviors()
            +expands_and_collapses_actions()
            +updates_action_status_indicators()
        }
        class BotInformationSection {
            +wraps_bot_metadata()
            +displays_bot_name()
            +displays_workspace_path()
            +displays_bot_directory_path()
            +displays_company_icon()
            +displays_panel_version()
            +renders_bot_selection()
            +handles_workspace_path_edits()
            +handles_bot_switching()
            +expands_and_collapses_section()
            +truncates_long_paths_with_ellipsis()
            +shows_full_path_in_tooltip()
        }
        class BotPanel {
            +wraps_active_bot()
            +contains_available_bots()
            +contains_sections()
            +renders_panel_html()
            +handles_user_messages()
            +manages_panel_lifecycle()
            +refreshes_display()
            +opens_files_in_editor()
        }
        class BotRegistry {
            +stores_available_bot_configurations()
            +validates_bot_names()
            +provides_bot_cli_paths()
        }
        class CliOutputAdapter {
            +parses_cli_json_output()
            +adapts_cli_data_to_panel_format()
            +extracts_behavior_hierarchy()
            +extracts_scope_information()
            +extracts_instructions_data()
        }
        class HtmlRenderer {
            +renders_complete_panel_html()
            +renders_bot_information_section()
            +renders_behavior_action_section()
            +renders_scope_section()
            +renders_instructions_section()
            +generates_javascript_for_webview_interactions()
            +escapes_html_entities()
        }
        class InstructionsSection {
            +wraps_current_instructions()
            +renders_base_instructions()
            +renders_clarify_instructions()
            +renders_strategy_instructions()
            +renders_build_instructions()
            +renders_validate_instructions()
            +renders_render_instructions()
            +renders_raw_instructions_format()
            +handles_instruction_submission_to_ai_chat()
            +handles_user_edits_to_questions()
            +handles_user_edits_to_assumptions()
            +validates_instructions_selected()
            +expands_and_collapses_section()
        }
        class ScopeSection {
            +wraps_story_graph_scope()
            +wraps_file_scope()
            +renders_story_hierarchy()
            +renders_file_list()
            +handles_story_search()
            +handles_file_pattern_search()
            +expands_and_collapses_story_nodes()
            +opens_story_graph_json()
            +opens_story_map_diagram()
            +opens_epic_folder()
            +opens_sub-epic_folder()
            +opens_test_file_at_class()
            +opens_test_file_at_scenario()
            +displays_hierarchical_matches()
            +clears_search()
        }
        class StatusDataProvider {
            +fetches_cli_status_via_python_subprocess()
            +switches_current_bot()
            +updates_workspace_path()
            +executes_cli_commands()
            +loads_bot_registry_from_json()
            +provides_available_bot_names()
        }
    }

    namespace ext {
        class Router {
            +match_trigger_patterns()
            +route_to_mcp_bot_tool()
            +route_to_behavior_tool()
            +route_to_action_tool()
            +forward_to_behavior()
            +forward_to_action()
            +forward_to_current_behavior_and_action()
        }
    }

    namespace repl_cli {
        class REPLSession {
            +runs_repl_loop()
            +reads_input_from_stdin_or_terminal()
            +parses_command_input()
            +routes_commands_to_cli_bot()
            +displays_status_and_results()
            +has_cli_bot()
        }
    }

    namespace repl_cli.cli_bot {
        class CLIAction {
            +get_name:_str()
            +get_description:_str()
            +is_current:_bool()
            +is_completed:_bool()
            +executes:_actionresult()
            +wraps_domain_action()
        }
        class CLIActions {
            +get_all:_list[cliaction]()
            +get_current:_cliaction()
            +find_by_name:_cliaction()
            +wraps_domain_actions()
        }
        class CLIBehavior {
            +get_name:_str()
            +get_description:_str()
            +get_actions:_cliactions()
            +is_current:_bool()
            +wraps_domain_behavior()
        }
        class CLIBehaviors {
            +get_all:_list[clibehavior]()
            +get_current:_clibehavior()
            +find_by_name:_clibehavior()
            +wraps_domain_behaviors()
        }
        class CLIBot {
            +get_name:_str()
            +get_workspace_directory:_path()
            +get_behaviors:_clibehaviors()
            +get_status_text:_str()
            +wraps_domain_bot()
        }
    }

    namespace workflow {
        class BehaviorGraphBuilder {
            +read_behavior_workflow_definitions()
            +create_langgraph_stategraph()
            +build_node_instances_from_actions()
            +connect_nodes_based_on_workflow_order()
        }
        class BotLangActionNode {
            +wrap_action.execute(context)_method()
            +implement_two-pass_pattern()
            +support_execution_modes()
            +provide_langgraph_entry_point()
        }
        class BotLangFlow {
            +execute_nodes_in_sequence()
            +handle_conditional_branching()
            +support_loops_and_iterations()
            +pause_at_interactive_points()
            +resume_from_checkpoint()
        }
        class BotLangFlowRunner {
            +load_botlangflow_python_files()
            +compile_graph_with_checkpointer()
            +execute_workflow_graph()
            +resume_from_checkpoint()
        }
        class BotLangState {
            +contain_story_graph()
            +contain_clarification_data()
            +contain_strategy_data()
            +contain_context_files()
            +contain_files_dictionary()
            +contain_workspace_directory()
            +contain_workflow_execution_state()
        }
        class BotMode {
            +determine_ai_interaction()
            +control_pause_points()
        }
        class Checkpoint {
            +save_workflow_state()
            +restore_workflow_state()
            +track_execution_history()
            +enable_resume_capability()
        }
    }

    
    %% Associations
    Base Bot --> Behavior : uses
    Base Bot --> Router : uses
    Base Bot --> Content : uses
    Specific Bot --> Behavior : uses
    BotLangActionNode --> BotMode : uses
    BehaviorGraphBuilder --> Behavior : uses
    BehaviorGraphBuilder --> BotLangState : uses
    BehaviorGraphBuilder --> BotLangActionNode : uses
    BotLangFlowRunner --> BotLangFlow : uses
    BotLangFlowRunner --> Checkpoint : uses
    BotLangFlowRunner --> BotLangActionNode : uses
    BotLangFlowRunner --> BotLangState : uses
    StoryBotMCPServer --> Behavior : uses
    BehaviorToolGenerator --> Behavior : uses
    ActionStateManager --> Behavior : uses
    Synchronizer --> Renderer : uses
    StoryIOEpic --> Template : uses
    StoryIOFeature --> Template : uses
    StoryIOStory --> Template : uses
    StoryIOIncrement --> Template : uses
    Router --> Base Bot : uses
    Router --> Behavior : uses
    Workflow State --> Behavior : uses
    Checkpoint --> BotLangState : uses
    Checkpoint --> BotLangFlowRunner : uses
    Checkpoint --> BotLangFlow : uses
    BotMode --> BotLangActionNode : uses
    BotLangFlow --> BotLangActionNode : uses
    BotLangFlow --> BotLangFlowRunner : uses
    BotLangFlow --> BotLangState : uses
    BotLangFlow --> BotMode : uses
    BotLangFlow --> Checkpoint : uses
    Behavior Action State --> Behavior : uses
    Behavior --> Rule : uses
    Behavior --> Content : uses
    Base Action --> Behavior : uses
    Base Action --> Content : uses
    BotPanel --> BotRegistry : uses
    BotPanel --> BotInformationSection : uses
    BotPanel --> BehaviorActionSection : uses
    BotPanel --> ScopeSection : uses
    BotPanel --> InstructionsSection : uses
    BotPanel --> HtmlRenderer : uses
    BotPanel --> StatusDataProvider : uses
    BotInformationSection --> BotRegistry : uses
    BotInformationSection --> StatusDataProvider : uses
    BehaviorActionSection --> Behavior : uses
    BehaviorActionSection --> StatusDataProvider : uses
    InstructionsSection --> Behavior : uses
    HtmlRenderer --> BotPanel : uses
    HtmlRenderer --> BotInformationSection : uses
    HtmlRenderer --> BehaviorActionSection : uses
    HtmlRenderer --> ScopeSection : uses
    HtmlRenderer --> InstructionsSection : uses
    StatusDataProvider --> BotRegistry : uses
    REPLSession --> CLIBot : uses
    CLIBot --> CLIBehaviors : uses
    CLIBot --> CLIBehavior : uses
    CLIBot --> CLIActions : uses
    CLIBot --> CLIAction : uses
    CLIBehaviors --> CLIBehavior : uses
    CLIBehavior --> CLIActions : uses
    CLIBehavior --> Behavior : uses
    CLIActions --> CLIAction : uses
    Behavior Workflow --> Behavior : uses
    GatherContextAction --> Behavior : uses
    GatherContextAction --> Guardrails : uses
    PlanningAction --> Behavior : uses
    PlanningAction --> Guardrails : uses
    BuildKnowledgeAction --> Behavior : uses
    BuildKnowledgeAction --> Content : uses
    Content --> Template : uses
    Content --> Renderer : uses
    Content --> Synchronizer : uses
    RenderOutputAction --> Behavior : uses
    RenderOutputAction --> Content : uses
    RenderOutputAction --> Renderer : uses
    RenderOutputAction --> Template : uses
    Renderer --> Template : uses
    Renderer --> Content : uses
    Template --> Content : uses
    Template --> Behavior : uses
    ValidateRulesAction --> Base Bot : uses
    ValidateRulesAction --> Behavior : uses
    ValidateRulesAction --> Content : uses
    Rule --> Behavior : uses
    Rule --> Base Bot : uses
    CorrectBotAction --> Behavior : uses
    CorrectBotAction --> Content : uses