apiVersion: apps/v1
kind: ContainerApp
metadata:
  name: vector-search
  namespace: augmented-teams
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vector-search
        feature: vector-search
    spec:
      containers:
      - name: vector-search
        image: augmentedteamacr.azurecr.io/vector-search:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
  service:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

